// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace hostcore.Entities
{
    [Table("brands", Schema = "production")]
    public partial class Brands
    {
        public Brands()
        {
            Products = new HashSet<Products>();
        }

        [Column("brand_id")]
        public int BrandId { get; set; }
        [Required]
        [Column("brand_name")]
        [StringLength(255)]
        public string BrandName { get; set; }

        [InverseProperty("Brand")]
        public virtual ICollection<Products> Products { get; set; }
    }
}