// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace hostcore.Entities
{
    [Table("products", Schema = "production")]
    public partial class Products
    {
        public Products()
        {
            Stocks = new HashSet<Stocks>();
        }

        [Column("product_id")]
        public int ProductId { get; set; }
        [Required]
        [Column("product_name")]
        [StringLength(255)]
        public string ProductName { get; set; }
        [Column("brand_id")]
        public int BrandId { get; set; }
        [Column("category_id")]
        public int CategoryId { get; set; }
        [Column("model_year")]
        public short ModelYear { get; set; }
        [Column("list_price", TypeName = "decimal(10, 2)")]
        public decimal ListPrice { get; set; }

        [ForeignKey("BrandId")]
        [InverseProperty("Products")]
        public virtual Brands Brand { get; set; }
        [ForeignKey("CategoryId")]
        [InverseProperty("Products")]
        public virtual Categories Category { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<Stocks> Stocks { get; set; }
    }
}